blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    # if we want to setup ID from sqlite
    path("<int:blog_id>/", views.detail, name='detail')
]

personal_portfolio/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from portfolio import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    author = models.CharField(max_length=50)
    date = models.DateField(null=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.


def all_blogs(request):
    blog_count = Blog.objects.count
    blogs = Blog.objects.order_by('-date')[:5]
    return render(request, 'blog/all_blogs.html', {'blogs': blogs, 'blog_count': blog_count})


def detail(request, blog_id):
    # pk = primary key
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">This is BLOG site</h1>
<br/>
<!-- here we use the variable from views.py just like 'blogs' -->
<!-- 'pluralize' is used if we want to check if the variable is 'singular' or 'plural' so we can write 'post' or 'posts' -->
<!-- .count in this case is a built-in method and not an part of blogs object-->

<h3 class="text-center mb-5">I have written for You {{ blog_count }} post{{ blogs.count|pluralize }} in this blog page</h3>
<br/>
<h3 class="text-center">Here is newest {{ blogs.count }} of them: </h3>

{% for blog in blogs %}
    <div>

        <!-- detail is the def detail (from views) run by blog (variable from urls)       -->
        <!-- because it is a good practice to name app : app_name = 'blog'       -->
<div class="row justify-content-center my-3 text-center">
  <div class="col-md-10">
              <p>---------------------------------------------------------------------</p>
        <a href="{% url 'blog:detail' blog.id %}"><h3>{{ blog.title }}</h3></a>
        <p>{{ blog.author }}</p>
        <!--    we can specify how many letter we want to see before we see ...    -->
        <!--    if we add 'safe' we can write to the blog stuf like <b>hell</b> and it will return bolded text    -->
        <!--    if we don;t ever want to see html tags we apply 'strip' instead of 'safe'    -->
        <p>{{ blog.content|safe|truncatechars:15 }}</p>

        <!-- we can setup dateformat  -->
        <!-- we can do it without the '|upper' or even without the year 'd M' or like this 'M d Y'      -->

        <h4>{{ blog.date|date:'d M Y'|upper }}</h4>
        <p>---------------------------------------------------------------------</p>
        </div>
</div>
    </div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}
<div class="text-center">
    <p>---------------------------------------------------------------------</p>
    <h1>{{ blog.title }}</h1>
    <br/>
    <h3>---{{ blog.date|date:'F jS Y' }}---</h3>
    <!--if we don;t give 'safe' or 'strip' we will get <b>...</b> -->
    <br/>
    <br/>
    <h3>{{ blog.content|safe }}</h3>
    <p>{{ blog.author }}</p>
    <p>---------------------------------------------------------------------</p>
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">

  <head>
    {% load static%}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'portfolio/Logo.png' %}">
    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">

    <title>Maciek</title>
  </head>

  <body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'portfolio/Logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Maciek Celiński</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/Maciej Celiński - CV.pdf' %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/nick-walter/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/ZappyCode" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/39-gaLbaZf.jpg' %}" class="img-fluid">
  </div>
</div>
<h2 class="mt-5">Portfolio of Maciek</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}






